# 安全配置主文件
# 整合所有安全相关配置的入口文件

# 配置文件引用
config_references:
  encryption_config: "./encryption.yaml"
  permission_config: "./permission.yaml"
  
# 全局安全设置
global_security:
  security_level: "high"  # low, medium, high, critical
  compliance_mode: true
  audit_enabled: true
  
# 认证配置
authentication:
  primary_method: "trae_native"
  backup_methods: ["ldap", "oauth2"]
  multi_factor_auth:
    enabled: true
    methods: ["totp", "sms", "email"]
    required_for_roles: ["system_admin", "project_manager"]
    
# 授权配置  
authorization:
  model: "role_based"
  inheritance_enabled: true
  dynamic_permissions: true
  
# 数据保护
data_protection:
  classification_levels:
    - "public"
    - "internal"
    - "confidential" 
    - "restricted"
  default_classification: "internal"
  data_loss_prevention: true
  
# 网络安全
network_security:
  firewall_enabled: true
  intrusion_detection: true
  traffic_monitoring: true
  allowed_protocols: ["https", "ssh", "sftp"]
  
# 监控和告警
security_monitoring:
  real_time_monitoring: true
  anomaly_detection: true
  threat_intelligence: true
  alert_channels: ["email", "sms", "dashboard"]
  
# 事件响应
incident_response:
  automated_response: true
  escalation_matrix:
    low: ["log", "notify_admin"]
    medium: ["log", "notify_admin", "restrict_access"]
    high: ["log", "notify_admin", "restrict_access", "isolate_system"]
    critical: ["log", "notify_admin", "restrict_access", "isolate_system", "emergency_shutdown"]
    
# 合规性检查
compliance_checks:
  automated_scanning: true
  scan_frequency: "daily"
  compliance_frameworks:
    - "ISO27001"
    - "GDPR"
    - "等保2.0"
    
# 安全培训
security_training:
  mandatory_training: true
  training_frequency: "quarterly"
  topics:
    - "密码安全"
    - "钓鱼邮件识别"
    - "数据分类处理"
    - "事件报告流程"
    
# 定期审查
security_reviews:
  access_review_frequency: "monthly"
  permission_audit_frequency: "quarterly"
  security_assessment_frequency: "annually"
  
# 备份和恢复安全
backup_security:
  backup_encryption: true
  offsite_backup: true
  recovery_testing: "monthly"
  
# 开发安全
development_security:
  secure_coding_standards: true
  code_review_required: true
  vulnerability_scanning: true
  dependency_checking: true