capabilities:
- spreadsheet_processing
- data_analysis
- report_generation
- financial_calculations
dependencies:
- openpyxl
- pandas
logging:
  backup_count: 5
  file: logs/excel_mcp.log
  level: INFO
  max_size: 10MB
performance:
  max_connections: 100
  retry_attempts: 3
  timeout: 30
security:
  authentication: true
  encryption: true
  rate_limiting: true
server_info:
  name: Excel MCP Server
  port: 3002
  protocol: stdio
  version: 1.0.0
