runtime:
  dependencies:
  - openpyxl
  - pandas
  - mcp
  environment: development
  python_version: 3.11+
server_info:
  capabilities:
  - spreadsheet_processing
  - data_analysis
  - report_generation
  name: Excel MCP Server
  protocol: stdio
  version: 1.0.0
