capabilities:
- database_connection
- query_execution
- data_management
- schema_operations
dependencies:
- sqlalchemy
- sqlite3
logging:
  backup_count: 5
  file: logs/database_mcp.log
  level: INFO
  max_size: 10MB
performance:
  max_connections: 100
  retry_attempts: 3
  timeout: 30
security:
  authentication: true
  encryption: true
  rate_limiting: true
server_info:
  name: Database MCP Server
  port: 3006
  protocol: stdio
  version: 1.0.0
