# 通用沟通协作配置
# 从 SharedWorkspace/Collaboration/workflows_config.yaml 迁移

communication:
  channels:
    meeting_system:
      minutes: true
      recording: true
      type: 会议系统
      usage: 正式会议和决策
    shared_documents:
      location: SharedWorkspace/Documents
      type: 文档协作
      usage: 文档共享和编辑
      version_control: true
    trae_workspace:
      format: 结构化消息
      participants: 所有智能体
      type: 实时协作
      usage: 日常工作交流
  escalation_rules:
    level_1:
      condition: 部门内部问题
      handler: 部门主管
      response_time: < 2小时
    level_2:
      condition: 跨部门协调问题
      handler: CEO
      response_time: < 4小时
    level_3:
      condition: 紧急业务问题
      handler: CEO + 相关部门
      response_time: < 30分钟
  message_formats:
    decision_proposal:
      template:
        content:
          alternatives: 备选方案
          impact: 影响分析
          proposal: 提议内容
          rationale: 理由说明
        sender: 提议者
        timestamp: 时间戳
        type: decision_proposal
    status_update:
      template:
        content:
          current_task: 当前任务
          issues: 遇到的问题
          next_steps: 下一步计划
          progress: 进度百分比
        sender: 智能体名称
        timestamp: 时间戳
        type: status_update
    task_request:
      template:
        content:
          deadline: 截止时间
          priority: 优先级
          resources: 所需资源
          task_description: 任务描述
        recipient: 接收者
        sender: 请求者
        timestamp: 时间戳
        type: task_request

decision_making:
  consensus_rules:
    qualified_majority:
      threshold: 66.7%
      usage: 重要决策
    simple_majority:
      threshold: 50% + 1
      usage: 一般性决策
    unanimous:
      threshold: 100%
      usage: 关键战略决策
  decision_process:
    analysis:
      description: 分析评估
      requirements:
      - 可行性分析
      - 风险评估
      - 成本效益
      responsible: 相关专家智能体
      step: 2
    consultation:
      description: 征求意见
      requirements:
      - 意见收集
      - 反馈整理
      responsible: 利益相关者
      step: 3
    decision:
      description: 做出决策
      requirements:
      - 决策结果
      - 执行计划
      responsible: 决策权限者
      step: 4
    execution:
      description: 执行监督
      requirements:
      - 执行进度
      - 效果评估
      responsible: 执行部门
      step: 5
    proposal:
      description: 提出决策提议
      requirements:
      - 问题描述
      - 解决方案
      - 影响分析
      responsible: 任何智能体
      step: 1

# 通用日志配置
logging:
  destinations:
  - console
  - file
  - database
  levels:
  - DEBUG
  - INFO
  - WARNING
  - ERROR
  - CRITICAL
  retention: 30天
  rotation: daily