backup:
  backup_retention_days: 30
  backup_type: daily
  enable_auto_backup: true
  exclude_patterns:
  - __pycache__
  - '*.pyc'
  - .venv
  - node_modules
  - bak
cleanup:
  auto_cleanup_temp: true
  cleanup_old_logs: true
  max_log_files: 50
git:
  auto_commit: true
  commit_prefix: 工作完成
  push_to_remote: true
  repository_name: YDS-Lab
reports:
  generate_daily_report: true
  include_ai_summary: true
  include_file_changes: true
  include_git_commits: true
