# Trae智能体协作配置
# 定义智能体之间的协作关系和工作流程

collaboration_matrix:
  # CEO作为核心协调者
  CEO:
    reports_to: []
    manages: ["PlanningDirector", "FinanceDirector", "DevTeamLead", "MarketingDirector", "ResourceAdmin"]
    collaboration_frequency: "daily"
    decision_authority: "final"
    
  # 企划总监 - 项目规划和需求分析
  PlanningDirector:
    reports_to: ["CEO"]
    collaborates_with: ["DevTeamLead", "MarketingDirector", "FinanceDirector"]
    specializes_in: ["项目规划", "需求分析", "方案设计"]
    deliverables: ["项目计划", "需求文档", "技术方案"]
    
  # 财务总监 - 财务管理和成本控制
  FinanceDirector:
    reports_to: ["CEO"]
    collaborates_with: ["PlanningDirector", "ResourceAdmin"]
    specializes_in: ["财务分析", "预算管理", "成本控制"]
    deliverables: ["财务报表", "预算方案", "成本分析"]
    
  # 开发团队负责人 - 技术实现和团队管理
  DevTeamLead:
    reports_to: ["CEO"]
    collaborates_with: ["PlanningDirector", "ResourceAdmin"]
    specializes_in: ["技术架构", "代码开发", "团队管理"]
    deliverables: ["技术文档", "代码实现", "测试报告"]
    
  # 市场总监 - 市场分析和推广策略
  MarketingDirector:
    reports_to: ["CEO"]
    collaborates_with: ["PlanningDirector", "ResourceAdmin"]
    specializes_in: ["市场分析", "推广策略", "用户研究"]
    deliverables: ["市场报告", "推广方案", "用户反馈"]
    
  # 资源行政 - 资源管理和行政支持
  ResourceAdmin:
    reports_to: ["CEO"]
    collaborates_with: ["FinanceDirector", "DevTeamLead", "MarketingDirector"]
    specializes_in: ["资源管理", "行政支持", "文档管理"]
    deliverables: ["资源报告", "行政文档", "会议纪要"]

# 工作流程定义
workflows:
  daily_standup:
    participants: ["CEO", "PlanningDirector", "FinanceDirector", "DevTeamLead", "MarketingDirector", "ResourceAdmin"]
    schedule: "09:00"
    duration: "30min"
    agenda: ["昨日进展", "今日计划", "问题讨论", "决策事项"]
    
  project_planning:
    initiator: "PlanningDirector"
    participants: ["CEO", "DevTeamLead", "FinanceDirector"]
    steps:
      1: "需求收集和分析"
      2: "技术方案设计"
      3: "资源和预算评估"
      4: "项目计划制定"
      5: "CEO审批和启动"
      
  code_review:
    initiator: "DevTeamLead"
    participants: ["DevTeamLead", "PlanningDirector"]
    automated_checks: true
    quality_gates: ["代码规范", "测试覆盖率", "安全检查"]
    
  financial_review:
    initiator: "FinanceDirector"
    participants: ["CEO", "FinanceDirector", "ResourceAdmin"]
    frequency: "weekly"
    reports: ["收支报告", "预算执行", "成本分析"]

# 通信协议
communication:
  channels:
    urgent: "Trae即时消息"
    normal: "共享工作空间"
    formal: "会议和文档"
    
  response_time:
    urgent: "15min"
    normal: "2hours"
    formal: "1day"
    
  escalation:
    level1: "直接协作者"
    level2: "部门负责人"
    level3: "CEO"

# 决策机制
decision_making:
  consensus_required: ["项目启动", "重大技术变更", "预算调整"]
  ceo_authority: ["人事决策", "战略方向", "紧急事项"]
  department_authority: ["日常运营", "技术细节", "执行计划"]
  
# 知识共享
knowledge_sharing:
  documentation: "Struc/SharedWorkspace/Documents"
  templates: "Struc/SharedWorkspace/Templates"
  best_practices: "Struc/SharedWorkspace/KnowledgeBase"
  
  update_frequency: "real_time"
  version_control: true
  access_control: "role_based"