def main():
    print("\n===== AUTOVPN使用帮助 =====")
    print("本系统提供多种上网模式，满足不同需求：")
    print("\n1. WireGuard模式:")
    print("   - 为WireGuard VPN提供UDP转发服务")
    print("   - 需要配置WireGuard客户端并导入配置文件")
    print("   - 适合需要全局VPN的场景")
    print("\n2. 代理模式:")
    print("   - 提供SOCKS5和HTTP代理服务")
    print("   - 可配合PAC文件实现智能分流")
    print("   - 适合浏览器和支持代理的应用程序")
    print("\n3. 综合模式:")
    print("   - 同时提供WireGuard UDP转发和代理服务")
    print("   - 适合既需要VPN又需要代理的场景")
    print("\n常见问题:")
    print("Q: 无法连接到服务器")
    print("A: 检查网络连接、服务器IP地址和防火墙设置")
    print("\nQ: WireGuard可以连接但无法上网")
    print("A: 检查WireGuard配置文件中的AllowedIPs设置")
    print("\nQ: 代理连接失败")
    print("A: 确保wstunnel正在运行，并检查代理端口是否正确")
    print("\nQ: 如何更新配置")
    print("A: 编辑config.env文件，然后运行配置同步脚本")
    print("\n更多帮助信息，请查看文档目录下的说明文件")
    print("================================")


if __name__ == "__main__":
    main()
