capabilities:
- project_building
- deployment_management
- ci_cd_integration
- environment_setup
dependencies:
- docker
- subprocess
logging:
  backup_count: 5
  file: logs/builder_mcp.log
  level: INFO
  max_size: 10MB
performance:
  max_connections: 100
  retry_attempts: 3
  timeout: 30
security:
  authentication: true
  encryption: true
  rate_limiting: true
server_info:
  name: Builder MCP Server
  port: 3004
  protocol: stdio
  version: 1.0.0
