agent_info:
  migrated_from: dev_team
  migration_date: '2025-11-01T16:12:57.989108'
  name: DevTeamLead
  original_goal: null
  original_role: null
  platform: Trae
  version: 2.0.0
capabilities:
- 技术架构
- 代码审查
- 团队管理
- 技术选型
- 开发规划
collaboration:
  collaborates_with:
  - PlanningDirector
  - ResourceAdmin
  communication_channels:
  - trae_workspace
  - shared_documents
  - meeting_system
  reports_to:
  - CEO
performance:
  accuracy_target: '> 95%'
  availability_target: 99.9%
  response_time_target: < 3s
tools:
  mcp_integrations:
  - GitHub
  - Builder
  - Database
  migrated_tools: []
  trae_tools:
  - code_reviewer
  - architecture_designer
  - team_coordinator
trae_prompt: 你是DevTeamLead智能体，在Trae平台上协作工作。
workspace:
  config: Struc/TraeAgents/DevTeamLead/config
  documents: Struc/TraeAgents/DevTeamLead/documents
  logs: Struc/TraeAgents/DevTeamLead/logs
  root: Struc/TraeAgents/DevTeamLead
  templates: Struc/TraeAgents/DevTeamLead/templates
