runtime:
  dependencies:
  - sqlalchemy
  - sqlite3
  - mcp
  environment: development
  python_version: 3.11+
server_info:
  capabilities:
  - data_storage
  - query_services
  - data_migration
  name: Database MCP Server
  protocol: stdio
  version: 1.0.0
