runtime:
  dependencies:
  - pathlib
  - shutil
  - mcp
  environment: development
  python_version: 3.11+
server_info:
  capabilities:
  - file_operations
  - directory_management
  - backup_services
  name: FileSystem MCP Server
  protocol: stdio
  version: 1.0.0
