runtime:
  dependencies:
  - github
  - requests
  - mcp
  environment: development
  python_version: 3.11+
server_info:
  capabilities:
  - repository_management
  - code_collaboration
  - version_control
  name: GitHub MCP Server
  protocol: stdio
  version: 1.0.0
