capabilities:
- repository_management
- code_collaboration
- version_control
- issue_tracking
dependencies:
- github
- requests
logging:
  backup_count: 5
  file: logs/github_mcp.log
  level: INFO
  max_size: 10MB
performance:
  max_connections: 100
  retry_attempts: 3
  timeout: 30
security:
  authentication: true
  encryption: true
  rate_limiting: true
server_info:
  name: GitHub MCP Server
  port: 3001
  protocol: stdio
  version: 1.0.0
